### ISSUE TITLE
org.apache.spark.Logging has been removed in Spark 2.0

### ISSUE THREAD

**Issue by FadiBitar** [ehsanmok/spark-lp#1]
Spark-lp includes and extends org.apache.spark.Logging on Spark 2.0.0.
The class however is no longer part of Spark since the 2.0 release, which has proven problematic when attempting to build spark-lp.

Spark release log for the 2.0 version: http://spark.apache.org/releases/spark-release-2-0-0.html

**Comment by ehsanmok** [comment]
Thanks, I've edited the sbt to 1.6 for now.
